### ISSUE TITLE
[BACK] Argumentaire

### ISSUE THREAD

**Issue by heticeric** [adebayo98/react-challenge-2#38]
Attention aux fautes d'orthographe !

> Choix du framework
Dans l'ojectif de creer une api rest pour nourrir nos interfaces utilisateurs, j'ai décidé de travailler avec le langage php et le framework symfony. En effet, php et node sont de nos jours les géants du web. Nous avons ici un projet avec beaucoup de logique de metier ce qui implique un gros travail de conception et de structuration. Php proposant une api de programmation orienter objet plus riche que le js (même avec typescript pour ma part) j'ai préféré utiliser ce dernier. Quand à symfony il est le framework php le plus populaire et surtout le plus rigoureux ce qui facilite énormenent la production du code respectant les normes SOLID.

A développer. Ce ne sont pas des raisons convaincantes.

> Gestion de la sécurité
L'infrastructure de notre projet (micro-service) nous impose la création d'application sans état pour identifier nos utilisateurs et autoriser leurs demandes. C'est ainsi que nous avons utiliser le protocole Jwt auquel nous avons définit un contrat (dp strategy) dans notre application qui est actuellement adapter avec la librairies lcobucci/jwt. j'ai choisi cette dernière car elle fait partir des seules que je n'ai pu attaquer avec les failles suivantes (Signature Stripping, Cross-Site Request Forgery, Cross Site Scripting, HMAC-Spoofing). Par ailleurs je souligne que nos jetons sont signés via des clefs publiques et privées ce qui permet de baisser très considérablement de risque d'une attaque par force brute pour compromettre nos jetons.

**Très bien**
Plus de détails seraient un plus !

**Comment by adebayo98** [comment]
Pouvez être plus précis sur le fait que mes raisons pour le choix du framework ne sont pas convaincantes ? Je ne vois vraiment pas pas pourquoi. Merci bien !

**Comment by heticeric** [comment]
Bien-sûr.

> Dans l'ojectif de creer une api rest pour nourrir nos interfaces utilisateurs, j'ai décidé de travailler avec le langage php et le framework symfony. En effet, php et node sont de nos jours les géants du web.

Peut-être aurait-il fallu parler de coût d'hébergement, de performances, de personnel.
Mais surtout donner quelques exemples et éventuellement argumenté avec des portions de code qui exposent des aspects phare.

> Nous avons ici un projet avec beaucoup de logique de metier ce qui implique un gros travail de conception et de structuration. Php proposant une api de programmation orienter objet plus riche que le js (même avec typescript pour ma part) j'ai préféré utiliser ce dernier.

OK, OOP. Mais encore ?
Qu'es-ce que l'orienté objet permet ?
Sur quoi vas-tu reposer ton approche ? Design patterns ? Principes architecturaux…

> Quand à symfony il est le framework php le plus populaire et surtout le plus rigoureux ce qui facilite énormenent la production du code respectant les normes SOLID.

On ne choisit pas un framework parce qu'il est populaire.
Il aurait judicieux de définir ce que la norme SOLID comporte comme points saillants.

Voilà pour quelques approches possibles.

**Comment by heticeric** [comment]
Voilà des exemples bien mieux étayés :
- https://github.com/ShonhTan/projet-w3/tree/master/api
- https://github.com/ayshiff/madu_gr_4/tree/develop/client

**Comment by heticeric** [comment]
Vois-tu la différence ?

**Comment by adebayo98** [comment]
La note m’importe peu, je ne travaille pour les notes mais pour apprendre, toutefois je ne partage vraiment pas votre avis et je préfère que nous en parlons de vive voix quand nous aurons l’occasion afin que vous mieux m’expliquez.

**Comment by heticeric** [comment]
Et puis, tu sais, j'ai **TOUJOURS** raison ;-P
