### ISSUE TITLE
[BACK] Documentation de l'API

### ISSUE THREAD

**Issue by heticeric** [adebayo98/react-challenge-2#39]
Merci de définir son emplacement.
Et la façon de la générer…

**Comment by adebayo98** [comment]
La documentation est dans le ficher swagger.yaml à la racine du dossier api. Il faut utiliser  https://editor.swagger.io/ <https://editor.swagger.io/>  pour la générer.

**Comment by heticeric** [comment]
> La documentation est dans le ficher swagger.yaml à la racine du dossier api. Il faut utiliser https://editor.swagger.io/ <https://editor.swagger.io/> pour la générer.

Tu veux rire ? Il y avait 5 points faciles à avoir sur cet aspect.

Et puis, une API sans documentation externe, ce n'est pas vraiment sérieux !
